// ITEM constant
export const ITEM_LOADING = 'ITEM_LOADING'
export const GET_ITEM = 'GET_ITEM'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const CHANGE_ITEM_STATUS = 'CHANGE_ITEM_STATUS'

// IS ACTION COMPLETE
export const IS_ACTION_COMPLETE = 'IS_ACTION_COMPLETE'

// ERROR constant
export const GET_ERROR = 'GET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// CATEGORY constant
export const CATEGORY_LOADING = 'CATEGORY_LOADING'
export const GET_CATEGORY = 'GET_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

// OFFICE constant
export const OFFICE_LOADING = 'OFFICE_LOADING'
export const GET_OFFICE = 'GET_OFFICE'
export const UPDATE_OFFICE = 'UPDATE_OFFICE'
export const SET_UPDATED = 'SET_UPDATED'
export const SET_BUTTON_DISABLED = 'SET_BUTTON_DISABLED'

// DEPARTMENT constant
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING'
export const GET_DEPARTMENT = 'GET_DEPARTMENT'
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const CHANGE_DEPARTMENT_STATUS = 'CHANGE_DEPARTMENT_STATUS'
